development:
  development:
  adapter: redis
  url: redis://localhost:6379
 
test:
  development:
  adapter: redis
  url: redis://localhost:6379
 
production:
  adapter: redis
  url: <%= ENV["REDISCLOUD_URL"] %>